/**
 * @description       :
 * @author            : Shatrughna.Salunke
 * @group             :
 * @last modified on  : 23-05-2021
 * @last modified by  : Shatrughna.Salunke
 * Modifications Log
 * Ver   Date         Author               Modification
 * 1.0   23-05-2021   Shatrughna.Salunke   Initial Version
 **/
public class AaaaaaaLogin{
	public Static String getData(){

		System.debug('variable: ');
		System.debug('Test');
		return null;
	} 
}