/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 05-21-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   05-21-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/

public   class   AccountAction {  
       /**
       * @description 
       * @author ChangeMeIn@UserSettingsUnder.SFDoc | 05-21-2021 
       **/
       public static void getData() {
            
       }
}